application: yardchartsdevelop
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /api/alarms.*
  script: bootstrap.app

- url: /css
  static_dir: app/css

- url: /img
  static_dir: app/img

- url: /js
  static_dir: app/js

- url: /lib
  static_dir: app/lib

- url: /partials
  static_dir: app/partials

- url: .*
  script: bootstrap.app

#static_files: app/index.html
#upload: app/index.html
